name: CI Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['hotreload', 'mypackage', 'external']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache uv installation
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/uv
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-uv-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-deps-${{ matrix.package }}-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Create virtual environment
      run: |
        uv venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        
    - name: Install common dependencies
      run: |
        uv pip install maturin pytest ruff pyright
    
    - name: Install hotreload dependencies & run lint
      if: matrix.package == 'hotreload'
      run: |
        cd hotreload
        if [ -f "pyproject.toml" ]; then
          uv pip install -e .
        fi
        cd ..
        make ci-lint-hotreload
        
    - name: Install mypackage dependencies & run lint
      if: matrix.package == 'mypackage'
      run: |
        cd mypackage/mypackage
        if [ -f "pyproject.toml" ]; then
          uv pip install -e .
        fi
        cd ../..
        make ci-lint-mypackage
        
    - name: Install external dependencies & run lint
      if: matrix.package == 'external'
      run: |
        cd mypackage/external-package
        if [ -f "pyproject.toml" ]; then
          uv pip install -e .
        fi
        cd ../..
        make ci-lint-external 